stages:
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw_data
    - src/data/make_dataset.py
    outs:
    - data/processed_data
  scale:
    cmd: python src/data/scaler.py
    deps:
    - data/processed_data
    - src/data/scaler.py
    outs:
    - data/scaled_data
  gridsearchcv:
    cmd: python src/models/gridsearch.py
    deps:
    - data/processed_data
    - data/scaled_data
    - src/models/gridsearch.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed_data
    - data/scaled_data
    - src/models/train.py
    outs:
    - models/trained_model.joblib
  eval:
    cmd: python src/models/eval.py
    deps:
    - data/processed_data
    - data/scaled_data
    - src/models/eval.py
    metrics:
    - metrics/scores.json:
        cache: false
